In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [32]:
dataset=pd.read_csv('winequality-red.csv')
dataset.dropna(how='any')
dataset['Overall Acidity']=(dataset['fixed acidity']+dataset['volatile acidity'])/2
dataset['Overall Sulfur Dioxide']=(dataset['free sulfur dioxide']+dataset['total sulfur dioxide'])/2
dataset['Quality']=dataset['quality']
df=dataset.drop(columns=['fixed acidity','volatile acidity','free sulfur dioxide','total sulfur dioxide','quality'])
df


citric acid  residual sugar  ...  Overall Sulfur Dioxide  Quality
0            0.00             1.9  ...                    22.5        5
1            0.00             2.6  ...                    46.0        5
2            0.04             2.3  ...                    34.5        5
3            0.56             1.9  ...                    38.5        6
4            0.00             1.9  ...                    22.5        5
...           ...             ...  ...                     ...      ...
1594         0.08             2.0  ...                    38.0        5
1595         0.10             2.2  ...                    45.0        6
1596         0.13             2.3  ...                    34.5        6
1597         0.12             2.0  ...                    38.0        5
1598         0.47             3.6  ...                    30.0        6

[1599 rows x 10 columns]

In [34]:
X=dataset.iloc[:,:-1].values
Y=dataset.iloc[:,-1].values

In [35]:
Y=Y.reshape(len(Y),1)

In [37]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.25,random_state=0)

In [38]:
from sklearn.svm import SVC
svc=SVC(kernel='linear',random_state=0)
svc.fit(X_train,Y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [39]:
y_pred = svc.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[6 6]
 [5 5]
 [7 7]
 [6 6]
 [5 5]
 [6 6]
 [5 5]
 [6 6]
 [4 4]
 [5 5]
 [5 5]
 [5 5]
 [6 6]
 [5 5]
 [6 6]
 [6 6]
 [7 7]
 [5 5]
 [5 5]
 [4 4]
 [7 7]
 [6 6]
 [6 6]
 [4 4]
 [6 6]
 [5 5]
 [5 5]
 [7 7]
 [5 5]
 [6 6]
 [5 5]
 [6 6]
 [5 5]
 [6 6]
 [7 7]
 [7 7]
 [5 5]
 [6 6]
 [6 6]
 [7 7]
 [5 5]
 [7 7]
 [6 6]
 [6 6]
 [5 5]
 [5 5]
 [6 6]
 [6 6]
 [6 6]
 [5 5]
 [5 5]
 [5 5]
 [6 6]
 [6 6]
 [6 6]
 [5 5]
 [5 5]
 [5 5]
 [6 6]
 [5 5]
 [5 5]
 [6 6]
 [6 6]
 [6 6]
 [5 5]
 [6 6]
 [5 5]
 [5 5]
 [6 6]
 [6 6]
 [6 6]
 [6 6]
 [4 4]
 [6 6]
 [5 5]
 [6 6]
 [5 5]
 [5 5]
 [5 5]
 [6 6]
 [6 6]
 [5 5]
 [6 6]
 [6 6]
 [6 6]
 [5 5]
 [6 6]
 [5 5]
 [5 5]
 [5 5]
 [5 5]
 [6 6]
 [4 4]
 [5 5]
 [7 7]
 [6 6]
 [6 6]
 [5 5]
 [6 6]
 [5 5]
 [8 8]
 [6 6]
 [6 6]
 [6 6]
 [5 5]
 [5 5]
 [5 5]
 [5 5]
 [7 7]
 [5 5]
 [6 6]
 [5 5]
 [7 7]
 [5 5]
 [6 6]
 [6 6]
 [6 6]
 [7 7]
 [6 6]
 [6 6]
 [5 5]
 [7 7]
 [5 5]
 [5 5]
 [6 6]
 [6 6]
 [5 5]
 [5 5]
 [5 5]
 [6 6]
 [6 6]
 [6 6]
 [6 6]
 [6 6]
 [6 6]
 [5 5]
 [6 6]
 [5 5]
 [8 8]
 [5 5]
 [6 6]
 [5 5]
 [6 6]

In [40]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, y_pred)
print(cm)
print(accuracy_score(Y_test, y_pred)*100)

[[  2   0   0   0   0   0]
 [  0  14   0   0   0   0]
 [  0   0 169   0   0   0]
 [  0   0   0 170   0   0]
 [  0   0   0   0  40   0]
 [  0   0   0   0   0   5]]
100.0
